### ISSUE TITLE
商家提现设置

### ISSUE THREAD

**Issue by cgkim** [y-vm/pangku.io#15]
昨天有人下了一单了，然后他们走了整个流程，财务觉得在微信商户打款比较方便，但是需要商家的 openid 和姓名，所以。

增加二个字段，一个填写 openid ， 一个填写姓名，微信打款用。

提示商家先关注酷养车然后这里可以取到微信帐号的openid  http://pangku.com/m/openid

**Comment by cgkim** [comment]
“
然后 下面要标注  操作方式
1.注册微信个人
2.关注酷养车 点击 酷养车 选择4s店入驻
3.点击获取openid
”

**Comment by y-vm** [comment]
@cgkim 加在 **/merchant/setting/payout** 吗？

**Comment by cgkim** [comment]
是的
