### ISSUE TITLE
Rails before_destroy

### ISSUE THREAD

**Issue by y-vm** [y-vm/pangku.io#6]
```ruby
app/models/accessory.rb

has_and_belongs_to_many :orders
has_and_belongs_to_many :upkeeps
before_destroy { self.upkeeps.clear }
before_destroy { self.orders.clear }
```

这里我不理解的地方是 `before_destroy` 后面的回调
假设，用户删除单一配件后，产生回调，那么，对应的 `upkeeps` 或 `orders` 会被 `clear`

`clear` 没有回调，但我理解是 `全部删除` 对吧？

**Comment by y-vm** [comment]
> collection.destroy(object, …)
Removes one or more objects from the collection by running destroy on each association in the join table, overriding any dependent option. This does not destroy the objects.

我目前认为关联是自动删除的

```sql
sqlite> SELECT * FROM users_vehicles;
59|5|24570|2015-07-08 17:28:13.252509|2015-07-08 17:28:13.252509
60|5|24580|2015-07-08 17:28:21.341942|2015-07-08 17:28:21.341942
61|5|25183|2015-07-08 17:28:27.765065|2015-07-08 17:28:27.765065
sqlite> SELECT * FROM users_vehicles;
59|5|24570|2015-07-08 17:28:13.252509|2015-07-08 17:28:13.252509
60|5|24580|2015-07-08 17:28:21.341942|2015-07-08 17:28:21.341942
```

以上是我删除 ID 为 25183 的 vehicle 后的结果

@cgkim

**Comment by y-vm** [comment]
如果 `has_and_belongs_to_many ` 足够智能，那么 `before_destroy` 并没什么作用

**Comment by cgkim** [comment]
嗯，好。你处理掉那些代码吧。

**Comment by y-vm** [comment]
@cgkim 我还没拉下来，你处理比较好

**Comment by cgkim** [comment]
OK
